package com.tk.quicksearch.settings.shared

import com.tk.quicksearch.search.core.SearchSection
import com.tk.quicksearch.search.core.SearchTarget
import com.tk.quicksearch.search.core.SearchViewModel
import com.tk.quicksearch.search.data.AppShortcutRepository.SearchTargetShortcutMode
import com.tk.quicksearch.searchEngines.AliasHandler
import com.tk.quicksearch.settings.AppShortcutsSettings.AppShortcutSource

internal data class SettingsRouteHandlers(
    val onBack: () -> Unit,
    val onToggleOverlayMode: (Boolean) -> Unit,
    val onPickCustomImage: () -> Unit,
    val onToggleDirectDial: (Boolean) -> Unit,
    val onToggleSection: (SearchSection, Boolean) -> Unit,
    val onOpenDirectSearchConfigure: () -> Unit,
    val onOpenAddAppShortcutDialog: () -> Unit,
    val onAddAppShortcutFromSource: (AppShortcutSource) -> Unit,
    val onAddAppDeepLinkShortcut: (String, String, String, String?) -> Unit,
    val onAddSearchTargetQueryShortcut: (SearchTarget, String, String, SearchTargetShortcutMode) -> Unit,
    val onAddHomeScreenWidget: () -> Unit,
    val onAddQuickSettingsTile: () -> Unit,
    val onSetDefaultAssistant: () -> Unit,
    val onToggleAssistantLaunchVoiceMode: (Boolean) -> Unit,
    val onRefreshApps: (Boolean) -> Unit,
    val onRefreshContacts: (Boolean) -> Unit,
    val onRefreshFiles: (Boolean) -> Unit,
    val onRequestUsagePermission: () -> Unit,
    val onRequestContactPermission: () -> Unit,
    val onRequestFilePermission: () -> Unit,
    val onRequestCalendarPermission: () -> Unit,
    val onRequestCallPermission: () -> Unit,
    val onRequestWallpaperPermission: () -> Unit,
)

internal fun buildSettingsScreenCallbacks(
    viewModel: SearchViewModel,
    handlers: SettingsRouteHandlers,
): SettingsScreenCallbacks =
    SettingsScreenCallbacks(
        onBack = handlers.onBack,
        onRemoveSuggestionExcludedApp = viewModel::unhideAppFromSuggestions,
        onRemoveResultExcludedApp = viewModel::unhideAppFromResults,
        onRemoveExcludedContact = viewModel::removeExcludedContact,
        onRemoveExcludedFile = viewModel::removeExcludedFile,
        onRemoveExcludedSetting = viewModel::removeExcludedSetting,
        onRemoveExcludedAppShortcut = viewModel::removeExcludedAppShortcut,
        onClearAllExclusions = viewModel::clearAllExclusions,
        onToggleSearchEngine = viewModel::setSearchTargetEnabled,
        onReorderSearchEngines = viewModel::reorderSearchTargets,
        onAddCustomSearchEngine = viewModel::addCustomSearchEngine,
        onUpdateCustomSearchEngine = viewModel::updateCustomSearchEngine,
        onDeleteCustomSearchEngine = viewModel::deleteCustomSearchEngine,
        onToggleFileType = viewModel::setFileTypeEnabled,
        onToggleFolders = viewModel::setShowFolders,
        onToggleSystemFiles = viewModel::setShowSystemFiles,
        onSetFolderWhitelistPatterns = viewModel::setFolderWhitelistPatterns,
        onSetFolderBlacklistPatterns = viewModel::setFolderBlacklistPatterns,
        onRemoveExcludedFileExtension = viewModel::removeExcludedFileExtension,
        onToggleOneHandedMode = viewModel::setOneHandedMode,
        onToggleBottomSearchBar = viewModel::setBottomSearchBarEnabled,
        onToggleOverlayMode = handlers.onToggleOverlayMode,
        onToggleOverlayBlurEffect = viewModel::setOverlayBlurEffectEnabled,
        onDismissOverlayAssistantTip = viewModel::dismissOverlayAssistantTip,
        setAliasCode = viewModel::setAlias,
        setAliasEnabled = viewModel::setAliasEnabled,
        onSetMessagingApp = viewModel::setMessagingApp,
        onSetCallingApp = viewModel::setCallingApp,
        onWallpaperBackgroundAlphaChange = viewModel::setWallpaperBackgroundAlpha,
        onWallpaperBlurRadiusChange = viewModel::setWallpaperBlurRadius,
        onSetAppTheme = viewModel::setAppTheme,
        onOverlayThemeIntensityChange = viewModel::setOverlayThemeIntensity,
        onSetAppThemeMode = viewModel::setAppThemeMode,
        onFontScaleMultiplierChange = viewModel::setFontScaleMultiplier,
        onSetBackgroundSource = viewModel::setBackgroundSource,
        onPickCustomImage = handlers.onPickCustomImage,
        onSelectIconPack = viewModel::setIconPackPackage,
        onSearchIconPacks = viewModel::searchIconPacks,
        onRefreshIconPacks = viewModel::refreshIconPacks,
        onToggleAppLabels = viewModel::setShowAppLabels,
        onSetPhoneAppGridColumns = viewModel::setPhoneAppGridColumns,
        onSetAppIconShape = viewModel::setAppIconShape,
        onSetLauncherAppIcon = viewModel::setLauncherAppIcon,
        onToggleThemedIcons = viewModel::setThemedIconsEnabled,
        onToggleDirectDial = handlers.onToggleDirectDial,
        onToggleSection = handlers.onToggleSection,
        onToggleSearchEngineCompactMode = viewModel::setSearchEngineCompactMode,
        onSetSearchEngineCompactRowCount = viewModel::setSearchEngineCompactRowCount,
        onToggleSearchEngineAliasSuffixEnabled = viewModel::setSearchEngineAliasSuffixEnabled,
        onToggleAliasTriggerAfterSpaceEnabled = viewModel::setAliasTriggerAfterSpaceEnabled,
        onSetAmazonDomain = viewModel::setAmazonDomain,
        onSetCalculatorAlias = { code ->
            viewModel.setAlias(AliasHandler.CALCULATOR_ALIAS_FEATURE_ID, code)
        },
        onSetUnitConverterAlias = { code ->
            viewModel.setAlias(AliasHandler.UNIT_CONVERTER_ALIAS_FEATURE_ID, code)
        },
        onSetDateCalculatorAlias = { code ->
            viewModel.setAlias(AliasHandler.DATE_CALCULATOR_ALIAS_FEATURE_ID, code)
        },
        onSetCurrencyConverterAlias = { code ->
            viewModel.setAlias(AliasHandler.CURRENCY_CONVERTER_ALIAS_FEATURE_ID, code)
        },
        onSetWordClockAlias = { code ->
            viewModel.setAlias(AliasHandler.WORD_CLOCK_ALIAS_FEATURE_ID, code)
        },
        onSetDictionaryAlias = { code ->
            viewModel.setAlias(AliasHandler.DICTIONARY_ALIAS_FEATURE_ID, code)
        },
        onSetSearchSectionAlias = { targetId, code ->
            viewModel.setAlias(targetId, code)
        },
        onToggleCalculator = viewModel::setCalculatorEnabled,
        onToggleUnitConverter = viewModel::setUnitConverterEnabled,
        onToggleDateCalculator = viewModel::setDateCalculatorEnabled,
        onToggleCurrencyConverter = viewModel::setCurrencyConverterEnabled,
        onToggleWordClock = viewModel::setWordClockEnabled,
        onToggleDictionary = viewModel::setDictionaryEnabled,
        onToggleAppSuggestions = viewModel::setAppSuggestionsEnabled,
        onToggleWebSuggestions = viewModel::setWebSuggestionsEnabled,
        onWebSuggestionsCountChange = viewModel::setWebSuggestionsCount,
        onToggleTopResultIndicator = viewModel::setTopResultIndicatorEnabled,
        onToggleOpenKeyboardOnLaunch = viewModel::setOpenKeyboardOnLaunchEnabled,
        onToggleClearQueryOnLaunch = viewModel::setClearQueryOnLaunchEnabled,
        onToggleAutoCloseOverlay = viewModel::setAutoCloseOverlayEnabled,
        onToggleWallpaperAccent = viewModel::setWallpaperAccentEnabled,
        onToggleRecentQueries = viewModel::setRecentQueriesEnabled,
        onSetGeminiApiKey = viewModel::setGeminiApiKey,
        onSetPersonalContext = viewModel::setPersonalContext,
        onSetGeminiModel = viewModel::setGeminiModel,
        onSetGeminiGroundingEnabled = viewModel::setGeminiGroundingEnabled,
        onRefreshAvailableGeminiModels = viewModel::refreshAvailableGeminiModels,
        onOpenDirectSearchConfigure = handlers.onOpenDirectSearchConfigure,
        onToggleAppShortcutEnabled = viewModel::setAppShortcutEnabled,
        onLaunchAppShortcut = viewModel::launchAppShortcut,
        onOpenAddAppShortcutDialog = handlers.onOpenAddAppShortcutDialog,
        onAddAppShortcutFromSource = handlers.onAddAppShortcutFromSource,
        onAddAppDeepLinkShortcut = handlers.onAddAppDeepLinkShortcut,
        onAddSearchTargetQueryShortcut = handlers.onAddSearchTargetQueryShortcut,
        onUpdateCustomAppShortcut = viewModel::updateCustomAppShortcut,
        onDeleteCustomAppShortcut = viewModel::deleteCustomAppShortcut,
        onLaunchDeviceSetting = viewModel::openSetting,
        onLaunchCalendarEvent = viewModel::openCalendarEvent,
        onRequestAppUninstall = viewModel::requestUninstall,
        onOpenAppInfo = viewModel::openAppInfo,
        onAddHomeScreenWidget = handlers.onAddHomeScreenWidget,
        onAddQuickSettingsTile = handlers.onAddQuickSettingsTile,
        onSetDefaultAssistant = handlers.onSetDefaultAssistant,
        onToggleAssistantLaunchVoiceMode = handlers.onToggleAssistantLaunchVoiceMode,
        onRefreshApps = handlers.onRefreshApps,
        onRefreshContacts = handlers.onRefreshContacts,
        onRefreshFiles = handlers.onRefreshFiles,
        onRequestUsagePermission = handlers.onRequestUsagePermission,
        onRequestContactPermission = handlers.onRequestContactPermission,
        onRequestFilePermission = handlers.onRequestFilePermission,
        onRequestCalendarPermission = handlers.onRequestCalendarPermission,
        onRequestCallPermission = handlers.onRequestCallPermission,
        onRequestWallpaperPermission = handlers.onRequestWallpaperPermission,
    )
