package com.tk.quicksearch.settings.shared

import com.tk.quicksearch.search.core.SearchTarget
import com.tk.quicksearch.search.core.AppIconShape
import com.tk.quicksearch.search.core.BackgroundSource
import com.tk.quicksearch.search.core.CallingApp
import com.tk.quicksearch.search.core.MessagingApp
import com.tk.quicksearch.search.core.AppTheme
import com.tk.quicksearch.search.core.SearchSection
import com.tk.quicksearch.search.data.AppShortcutRepository.SearchTargetShortcutMode
import com.tk.quicksearch.search.data.AppShortcutRepository.StaticShortcut
import com.tk.quicksearch.search.models.AppInfo
import com.tk.quicksearch.search.models.CalendarEventInfo
import com.tk.quicksearch.search.models.ContactInfo
import com.tk.quicksearch.search.models.DeviceFile
import com.tk.quicksearch.search.models.FileType
import com.tk.quicksearch.search.core.IconPackInfo
import com.tk.quicksearch.search.deviceSettings.DeviceSetting
import com.tk.quicksearch.settings.AppShortcutsSettings.AppShortcutSource
import com.tk.quicksearch.tools.directSearch.GeminiTextModel

/**
 * Data class to hold all settings screen state and callbacks. Reduces parameter count and improves
 * maintainability.
 */
data class SettingsScreenState(
    val suggestionExcludedApps: List<AppInfo>,
    val resultExcludedApps: List<AppInfo>,
    val excludedContacts: List<ContactInfo>,
    val excludedFiles: List<DeviceFile>,
    val excludedSettings: List<DeviceSetting>,
    val excludedAppShortcuts: List<StaticShortcut>,
    val searchEngineOrder: List<SearchTarget>,
    val disabledSearchEngines: Set<String>,
    val enabledFileTypes: Set<FileType>,
    val showFolders: Boolean,
    val showSystemFiles: Boolean,
    val folderWhitelistPatterns: Set<String>,
    val folderBlacklistPatterns: Set<String>,
    val excludedFileExtensions: Set<String>,
    val oneHandedMode: Boolean,
    val bottomSearchBarEnabled: Boolean = false,
    val overlayModeEnabled: Boolean,
    val hasSeenOverlayAssistantTip: Boolean = true,
    val shortcutCodes: Map<String, String>,
    val shortcutEnabled: Map<String, Boolean>,
    val allAppShortcuts: List<StaticShortcut>,
    val allDeviceSettings: List<DeviceSetting>,
    val allApps: List<AppInfo>,
    val disabledAppShortcutIds: Set<String>,
    val messagingApp: MessagingApp,
    val callingApp: CallingApp,
    val isWhatsAppInstalled: Boolean,
    val isTelegramInstalled: Boolean,
    val isSignalInstalled: Boolean,
    val isGoogleMeetInstalled: Boolean,
    val hasWallpaperPermission: Boolean,
    val wallpaperAvailable: Boolean,
    val wallpaperBackgroundAlpha: Float,
    val wallpaperBlurRadius: Float,
    val appTheme: AppTheme,
    val overlayThemeIntensity: Float,
    val appThemeMode: com.tk.quicksearch.search.core.AppThemeMode,
    val fontScaleMultiplier: Float,
    val backgroundSource: BackgroundSource,
    val customImageUri: String?,
    val selectedIconPackPackage: String? = null,
    val availableIconPacks: List<IconPackInfo> = emptyList(),
    val showAppLabels: Boolean = true,
    val phoneAppGridColumns: Int = com.tk.quicksearch.search.data.preferences.UiPreferences.DEFAULT_PHONE_APP_GRID_COLUMNS,
    val appIconShape: AppIconShape = AppIconShape.DEFAULT,
    val directDialEnabled: Boolean,
    val disabledSections: Set<SearchSection>,
    val isSearchEngineCompactMode: Boolean,
    val searchEngineCompactRowCount: Int,
    val isSearchEngineAliasSuffixEnabled: Boolean,
    val isAliasTriggerAfterSpaceEnabled: Boolean,
    val amazonDomain: String? = null,
    val calculatorEnabled: Boolean,
    val unitConverterEnabled: Boolean,
    val dateCalculatorEnabled: Boolean,
    val appSuggestionsEnabled: Boolean,
    val webSuggestionsEnabled: Boolean,
    val webSuggestionsCount: Int,
    val topResultIndicatorEnabled: Boolean,
    val openKeyboardOnLaunch: Boolean,
    val clearQueryOnLaunch: Boolean,
    val autoCloseOverlay: Boolean,
    val recentQueriesEnabled: Boolean,
    val hasGeminiApiKey: Boolean = false,
    val geminiApiKeyLast4: String? = null,
    val isSavingGeminiApiKey: Boolean = false,
    val personalContext: String = "",
    val geminiModel: String,
    val geminiGroundingEnabled: Boolean,
    val availableGeminiModels: List<GeminiTextModel>,
)

/** Data class to hold all settings screen callbacks. */
data class SettingsScreenCallbacks(
    val onBack: () -> Unit,
    val onRemoveSuggestionExcludedApp: (AppInfo) -> Unit,
    val onRemoveResultExcludedApp: (AppInfo) -> Unit,
    val onRemoveExcludedContact: (ContactInfo) -> Unit,
    val onRemoveExcludedFile: (DeviceFile) -> Unit,
    val onRemoveExcludedSetting: (DeviceSetting) -> Unit,
    val onRemoveExcludedAppShortcut: (StaticShortcut) -> Unit,
    val onClearAllExclusions: () -> Unit,
    val onToggleSearchEngine: (SearchTarget, Boolean) -> Unit,
    val onReorderSearchEngines: (List<SearchTarget>) -> Unit,
    val onAddCustomSearchEngine: (String, String, String) -> Unit,
    val onUpdateCustomSearchEngine: (String, String, String, String?) -> Unit,
    val onDeleteCustomSearchEngine: (String) -> Unit,
    val onToggleFileType: (FileType, Boolean) -> Unit,
    val onToggleFolders: (Boolean) -> Unit,
    val onToggleSystemFiles: (Boolean) -> Unit,
    val onSetFolderWhitelistPatterns: (Set<String>) -> Unit,
    val onSetFolderBlacklistPatterns: (Set<String>) -> Unit,
    val onRemoveExcludedFileExtension: (String) -> Unit,
    val onToggleOneHandedMode: (Boolean) -> Unit,
    val onToggleBottomSearchBar: (Boolean) -> Unit,
    val onToggleOverlayMode: (Boolean) -> Unit,
    val onDismissOverlayAssistantTip: () -> Unit,
    val setAliasCode: (SearchTarget, String) -> Unit,
    val setAliasEnabled: (SearchTarget, Boolean) -> Unit,
    val onSetMessagingApp: (MessagingApp) -> Unit,
    val onSetCallingApp: (CallingApp) -> Unit,
    val onWallpaperBackgroundAlphaChange: (Float) -> Unit,
    val onWallpaperBlurRadiusChange: (Float) -> Unit,
    val onSetAppTheme: (AppTheme) -> Unit,
    val onOverlayThemeIntensityChange: (Float) -> Unit,
    val onSetAppThemeMode: (com.tk.quicksearch.search.core.AppThemeMode) -> Unit,
    val onFontScaleMultiplierChange: (Float) -> Unit,
    val onSetBackgroundSource: (BackgroundSource) -> Unit,
    val onPickCustomImage: () -> Unit,
    val onSelectIconPack: (String?) -> Unit,
    val onSearchIconPacks: () -> Unit,
    val onRefreshIconPacks: () -> Unit,
    val onToggleAppLabels: (Boolean) -> Unit,
    val onSetPhoneAppGridColumns: (Int) -> Unit,
    val onSetAppIconShape: (AppIconShape) -> Unit,
    val onToggleDirectDial: (Boolean) -> Unit,
    val onToggleSection: (SearchSection, Boolean) -> Unit,
    val onToggleSearchEngineCompactMode: (Boolean) -> Unit,
    val onSetSearchEngineCompactRowCount: (Int) -> Unit,
    val onToggleSearchEngineAliasSuffixEnabled: (Boolean) -> Unit,
    val onToggleAliasTriggerAfterSpaceEnabled: (Boolean) -> Unit,
    val onSetAmazonDomain: (String?) -> Unit,
    val onSetCalculatorAlias: (String) -> Unit,
    val onSetUnitConverterAlias: (String) -> Unit,
    val onSetDateCalculatorAlias: (String) -> Unit,
    val onSetSearchSectionAlias: (String, String) -> Unit,
    val onToggleCalculator: (Boolean) -> Unit,
    val onToggleUnitConverter: (Boolean) -> Unit,
    val onToggleDateCalculator: (Boolean) -> Unit,
    val onToggleAppSuggestions: (Boolean) -> Unit,
    val onToggleWebSuggestions: (Boolean) -> Unit,
    val onWebSuggestionsCountChange: (Int) -> Unit,
    val onToggleTopResultIndicator: (Boolean) -> Unit,
    val onToggleOpenKeyboardOnLaunch: (Boolean) -> Unit,
    val onToggleClearQueryOnLaunch: (Boolean) -> Unit,
    val onToggleAutoCloseOverlay: (Boolean) -> Unit,
    val onToggleRecentQueries: (Boolean) -> Unit,
    val onSetGeminiApiKey: (String?) -> Unit,
    val onSetPersonalContext: (String?) -> Unit,
    val onSetGeminiModel: (String?) -> Unit,
    val onSetGeminiGroundingEnabled: (Boolean) -> Unit,
    val onRefreshAvailableGeminiModels: () -> Unit,
    val onOpenDirectSearchConfigure: () -> Unit,
    val onToggleAppShortcutEnabled: (StaticShortcut, Boolean) -> Unit,
    val onLaunchAppShortcut: (StaticShortcut) -> Unit,
    val onOpenAddAppShortcutDialog: () -> Unit,
    val onAddAppShortcutFromSource: (AppShortcutSource) -> Unit,
    val onAddAppDeepLinkShortcut: (String, String, String, String?) -> Unit,
    val onAddSearchTargetQueryShortcut: (SearchTarget, String, String, SearchTargetShortcutMode) -> Unit,
    val onUpdateCustomAppShortcut: (StaticShortcut, String, String?, String?) -> Unit,
    val onDeleteCustomAppShortcut: (StaticShortcut) -> Unit,
    val onLaunchDeviceSetting: (DeviceSetting) -> Unit,
    val onLaunchCalendarEvent: (CalendarEventInfo) -> Unit,
    val onRequestAppUninstall: (AppInfo) -> Unit,
    val onOpenAppInfo: (AppInfo) -> Unit,
    val onAddHomeScreenWidget: () -> Unit,
    val onAddQuickSettingsTile: () -> Unit,
    val onSetDefaultAssistant: () -> Unit,
    val onToggleAssistantLaunchVoiceMode: (Boolean) -> Unit,
    val onRefreshApps: (Boolean) -> Unit,
    val onRefreshContacts: (Boolean) -> Unit,
    val onRefreshFiles: (Boolean) -> Unit,
    val onRequestUsagePermission: () -> Unit,
    val onRequestContactPermission: () -> Unit,
    val onRequestFilePermission: () -> Unit,
    val onRequestCalendarPermission: () -> Unit,
    val onRequestCallPermission: () -> Unit,
    val onRequestWallpaperPermission: () -> Unit,
)
