package com.tk.quicksearch.search.core

import com.tk.quicksearch.search.data.StartupPreferencesFacade
import com.tk.quicksearch.search.models.AppInfo
import com.tk.quicksearch.search.models.FileType
import java.util.concurrent.atomic.AtomicBoolean

internal data class SearchRuntimeState(
    var cachedAllSearchableApps: List<AppInfo> = emptyList(),
    @Volatile var startupConfig: StartupPreferencesFacade.StartupConfig? = null,
    val isAppShortcutsLoadInFlight: AtomicBoolean = AtomicBoolean(false),
    val hasStartedStartupPhases: AtomicBoolean = AtomicBoolean(false),
    @Volatile var resumeNeedsStaticDataRefresh: Boolean = false,
    @Volatile var lastBrowserTargetRefreshMs: Long = 0L,
    var prefCache: SearchPreferenceCache,
    var enabledFileTypes: Set<FileType> = emptySet(),
    var showFolders: Boolean = false,
    var showSystemFiles: Boolean = false,
    var folderWhitelistPatterns: Set<String> = emptySet(),
    var folderBlacklistPatterns: Set<String> = emptySet(),
    var excludedFileExtensions: Set<String> = emptySet(),
    var oneHandedMode: Boolean = false,
    var bottomSearchBarEnabled: Boolean = false,
    var topResultIndicatorEnabled: Boolean = true,
    var wallpaperAccentEnabled: Boolean = true,
    var openKeyboardOnLaunch: Boolean = true,
    var overlayModeEnabled: Boolean = false,
    var autoCloseOverlay: Boolean = true,
    var directDialEnabled: Boolean = false,
    var assistantLaunchVoiceModeEnabled: Boolean = false,
    var hasSeenDirectDialChoice: Boolean = false,
    var appSuggestionsEnabled: Boolean = true,
    var showAppLabels: Boolean = true,
    var phoneAppGridColumns: Int,
    var appIconShape: AppIconShape = AppIconShape.DEFAULT,
    var launcherAppIcon: LauncherAppIcon = LauncherAppIcon.DEFAULT,
    var themedIconsEnabled: Boolean = false,
    var deviceThemeEnabled: Boolean = false,
    var wallpaperBackgroundAlpha: Float,
    var wallpaperBlurRadius: Float,
    var appTheme: AppTheme = AppTheme.MONOCHROME,
    var overlayThemeIntensity: Float,
    var fontScaleMultiplier: Float,
    var useSystemFont: Boolean = false,
    var backgroundSource: BackgroundSource = BackgroundSource.THEME,
    var customImageUri: String? = null,
    var lockedShortcutTarget: SearchTarget? = null,
    var lockedAliasSearchSection: SearchSection? = null,
    var lockedToolMode: SearchToolType? = null,
    var lockedCurrencyConverterAlias: Boolean = false,
    var lockedWordClockAlias: Boolean = false,
    var lockedDictionaryAlias: Boolean = false,
    var lockedCustomToolId: String? = null,
    var clearQueryOnLaunch: Boolean = false,
    var amazonDomain: String? = null,
    var pendingNavigationClear: Boolean = false,
    var isStartupComplete: Boolean = false,
    var wallpaperAvailable: Boolean = false,
    @Volatile var shouldRecordPendingAiSearchQueryInHistory: Boolean = true,
)
