package com.tk.quicksearch.search.core

internal object SearchStateExtractor {
    fun extractResultsState(s: SearchUiState) =
        SearchResultsState(
            query = s.query,
            recentApps = s.recentApps,
            newOrUpdatedApps = s.newOrUpdatedApps,
            mostUsedApps = s.mostUsedApps,
            searchResults = s.searchResults,
            pendingSearchResults = s.pendingSearchResults,
            pinnedApps = s.pinnedApps,
            pinnedNonAppItemOrder = s.pinnedNonAppItemOrder,
            allApps = s.allApps,
            suggestionExcludedApps = s.suggestionExcludedApps,
            resultExcludedApps = s.resultExcludedApps,
            indexedAppCount = s.indexedAppCount,
            cacheLastUpdatedMillis = s.cacheLastUpdatedMillis,
            appShortcutResults = s.appShortcutResults,
            allAppShortcuts = s.allAppShortcuts,
            pinnedAppShortcuts = s.pinnedAppShortcuts,
            excludedAppShortcuts = s.excludedAppShortcuts,
            contactResults = s.contactResults,
            pinnedContacts = s.pinnedContacts,
            excludedContacts = s.excludedContacts,
            fileResults = s.fileResults,
            pinnedFiles = s.pinnedFiles,
            excludedFiles = s.excludedFiles,
            settingResults = s.settingResults,
            appSettingResults = s.appSettingResults,
            allDeviceSettings = s.allDeviceSettings,
            pinnedSettings = s.pinnedSettings,
            excludedSettings = s.excludedSettings,
            calendarEvents = s.calendarEvents,
            pinnedCalendarEvents = s.pinnedCalendarEvents,
            excludedCalendarEvents = s.excludedCalendarEvents,
            todayCalendarEvents = s.todayCalendarEvents,
            noteResults = s.noteResults,
            pinnedNotes = s.pinnedNotes,
            screenState = s.screenState,
            appsSectionState = s.appsSectionState,
            appShortcutsSectionState = s.appShortcutsSectionState,
            contactsSectionState = s.contactsSectionState,
            filesSectionState = s.filesSectionState,
            settingsSectionState = s.settingsSectionState,
            calendarSectionState = s.calendarSectionState,
            notesSectionState = s.notesSectionState,
            searchEnginesState = s.searchEnginesState,
            calculatorState = s.calculatorState,
            currencyConverterState = s.currencyConverterState,
            wordClockState = s.wordClockState,
            dictionaryState = s.dictionaryState,
            AiSearchState = s.AiSearchState,
            webSuggestions = s.webSuggestions,
            webSuggestionsLoading = s.webSuggestionsLoading,
            webSuggestionWasSelected = s.webSuggestionWasSelected,
            isAppSearchInProgress = s.isAppSearchInProgress,
            isSecondarySearchInProgress = s.isSecondarySearchInProgress,
            detectedShortcutTarget = s.detectedShortcutTarget,
            detectedAliasSearchSection = s.detectedAliasSearchSection,
            isCurrencyConverterAliasMode = s.isCurrencyConverterAliasMode,
            isWordClockAliasMode = s.isWordClockAliasMode,
            isDictionaryAliasMode = s.isDictionaryAliasMode,
            detectedCustomToolId = s.detectedCustomToolId,
            recentItems = s.recentItems,
            aliasRecentItems = s.aliasRecentItems,
            recentResultRecencyIndex = s.recentResultRecencyIndex,
            nicknameUpdateVersion = s.nicknameUpdateVersion,
            contactActionsVersion = s.contactActionsVersion,
        )

    fun extractPermissionState(s: SearchUiState) =
        SearchPermissionState(
            hasUsagePermission = s.hasUsagePermission,
            hasContactPermission = s.hasContactPermission,
            hasFilePermission = s.hasFilePermission,
            hasCalendarPermission = s.hasCalendarPermission,
            hasCallPermission = s.hasCallPermission,
            hasWallpaperPermission = s.hasWallpaperPermission,
            wallpaperAvailable = s.wallpaperAvailable,
            messagingApp = s.messagingApp,
            callingApp = s.callingApp,
            isWhatsAppInstalled = s.isWhatsAppInstalled,
            isTelegramInstalled = s.isTelegramInstalled,
            isSignalInstalled = s.isSignalInstalled,
            isGoogleMeetInstalled = s.isGoogleMeetInstalled,
        )

    fun extractFeatureState(s: SearchUiState) =
        SearchFeatureState(
            searchTargetsOrder = s.searchTargetsOrder,
            disabledSearchTargetIds = s.disabledSearchTargetIds,
            isSearchEngineCompactMode = s.isSearchEngineCompactMode,
            searchEngineCompactRowCount = s.searchEngineCompactRowCount,
            isSearchEngineAliasSuffixEnabled = s.isSearchEngineAliasSuffixEnabled,
            isAliasTriggerAfterSpaceEnabled = s.isAliasTriggerAfterSpaceEnabled,
            amazonDomain = s.amazonDomain,
            shortcutsEnabled = s.shortcutsEnabled,
            shortcutCodes = s.shortcutCodes,
            shortcutEnabled = s.shortcutEnabled,
            disabledAppShortcutIds = s.disabledAppShortcutIds,
            disabledSections = s.disabledSections,
            hasApiKey = s.hasApiKey,
            geminiApiKeyLast4 = s.geminiApiKeyLast4,
            llmApiKeyLast4ByProvider = s.llmApiKeyLast4ByProvider,
            customLlmBaseUrlByProvider = s.customLlmBaseUrlByProvider,
            customLlmAdvancedPayloadByProvider = s.customLlmAdvancedPayloadByProvider,
            aiSearchLlmProviderId = s.aiSearchLlmProviderId,
            personalContext = s.personalContext,
            geminiModel = s.geminiModel,
            geminiGroundingEnabled = s.geminiGroundingEnabled,
            geminiThinkingEnabled = s.geminiThinkingEnabled,
            availableGeminiModels = s.availableGeminiModels,
            availableLlmModelsByProvider = s.availableLlmModelsByProvider,
            webSuggestionsEnabled = s.webSuggestionsEnabled,
            webSuggestionsCount = s.webSuggestionsCount,
            calculatorEnabled = s.calculatorEnabled,
            unitConverterEnabled = s.unitConverterEnabled,
            dateCalculatorEnabled = s.dateCalculatorEnabled,
            currencyConverterEnabled = s.currencyConverterEnabled,
            wordClockEnabled = s.wordClockEnabled,
            dictionaryEnabled = s.dictionaryEnabled,
            customTools = s.customTools,
            disabledCustomToolIds = s.disabledCustomToolIds,
            recentQueriesEnabled = s.recentQueriesEnabled,
            topMatchesEnabled = s.topMatchesEnabled,
            topMatchesLimit = s.topMatchesLimit,
            topMatchesSectionOrder = s.topMatchesSectionOrder,
            disabledTopMatchesSections = s.disabledTopMatchesSections,
            showTodayEvents = s.showTodayEvents,
            hasDismissedSearchHistoryTip = s.hasDismissedSearchHistoryTip,
            directDialEnabled = s.directDialEnabled,
            shouldShowUsagePermissionBanner = s.shouldShowUsagePermissionBanner,
            showRateQuickSearchCard = s.showRateQuickSearchCard,
        )

    fun extractConfigState(s: SearchUiState) =
        SearchUiConfigState(
            startupPhase = s.startupPhase,
            isInitializing = s.isInitializing,
            isLoading = s.isLoading,
            errorMessage = s.errorMessage,
            isStartupCoreSurfaceReady = s.isStartupCoreSurfaceReady,
            showWallpaperBackground = s.showWallpaperBackground,
            wallpaperBackgroundAlpha = s.wallpaperBackgroundAlpha,
            wallpaperBlurRadius = s.wallpaperBlurRadius,
            appTheme = s.appTheme,
            overlayThemeIntensity = s.overlayThemeIntensity,
            appThemeMode = s.appThemeMode,
            backgroundSource = s.backgroundSource,
            customImageUri = s.customImageUri,
            startupBackgroundPreviewPath = s.startupBackgroundPreviewPath,
            overlayModeEnabled = s.overlayModeEnabled,
            oneHandedMode = s.oneHandedMode,
            bottomSearchBarEnabled = s.bottomSearchBarEnabled,
            unifiedPinnedItemsEnabled = s.unifiedPinnedItemsEnabled,
            searchHintsEnabled = s.searchHintsEnabled,
            settingsIconEnabled = s.settingsIconEnabled,
            topResultIndicatorEnabled = s.topResultIndicatorEnabled,
            wallpaperAccentEnabled = s.wallpaperAccentEnabled,
            openKeyboardOnLaunch = s.openKeyboardOnLaunch,
            clearQueryOnLaunch = s.clearQueryOnLaunch,
            autoCloseOverlay = s.autoCloseOverlay,
            fontScaleMultiplier = s.fontScaleMultiplier,
            useSystemFont = s.useSystemFont,
            showAppLabels = s.showAppLabels,
            phoneAppGridColumns = s.phoneAppGridColumns,
            appIconSizeStep = s.appIconSizeStep,
            appIconShape = s.appIconShape,
            launcherAppIcon = s.launcherAppIcon,
            themedIconsEnabled = s.themedIconsEnabled,
            deviceThemeEnabled = s.deviceThemeEnabled,
            appSuggestionsEnabled = s.appSuggestionsEnabled,
            showAllAppsButton = s.showAllAppsButton,
            includeNonLaunchableAppsInSearch = s.includeNonLaunchableAppsInSearch,
            selectedAppSuggestionTab = s.selectedAppSuggestionTab,
            enabledAppSuggestionTabs = s.enabledAppSuggestionTabs,
            selectedIconPackPackage = s.selectedIconPackPackage,
            availableIconPacks = s.availableIconPacks,
            maskUnsupportedIconPackIcons = s.maskUnsupportedIconPackIcons,
            enabledFileTypes = s.enabledFileTypes,
            showFolders = s.showFolders,
            filePreviewsEnabled = s.filePreviewsEnabled,
            showSystemFiles = s.showSystemFiles,
            folderWhitelistPatterns = s.folderWhitelistPatterns,
            folderBlacklistPatterns = s.folderBlacklistPatterns,
            excludedFileExtensions = s.excludedFileExtensions,
            showSearchEngineOnboarding = s.showSearchEngineOnboarding,
            showStartSearchingOnOnboarding = s.showStartSearchingOnOnboarding,
            showSearchBarWelcomeAnimation = s.showSearchBarWelcomeAnimation,
            showContactActionHint = s.showContactActionHint,
            hasSeenOverlayAssistantTip = s.hasSeenOverlayAssistantTip,
            showReleaseNotesDialog = s.showReleaseNotesDialog,
            releaseNotesVersionName = s.releaseNotesVersionName,
            phoneNumberSelection = s.phoneNumberSelection,
            directDialChoice = s.directDialChoice,
            contactMethodsBottomSheet = s.contactMethodsBottomSheet,
            contactActionPickerRequest = s.contactActionPickerRequest,
            pendingDirectCallNumber = s.pendingDirectCallNumber,
            pendingThirdPartyCall = s.pendingThirdPartyCall,
        )

    fun applyContactActionHint(
        updated: SearchUiState,
        hasSeenContactActionHint: Boolean,
    ): SearchUiState {
        val hasContacts = updated.contactResults.isNotEmpty() || updated.pinnedContacts.isNotEmpty()
        val shouldShowHint =
            hasContacts &&
                updated.hasContactPermission &&
                !updated.showContactActionHint &&
                !hasSeenContactActionHint

        return if (shouldShowHint) updated.copy(showContactActionHint = true) else updated
    }
}
