package com.tk.quicksearch.settings.shared

import com.tk.quicksearch.search.core.CustomTool
import com.tk.quicksearch.search.core.SearchUiState
import com.tk.quicksearch.tools.aiSearch.AiSearchLlmProviderId

internal fun SearchUiState.toSettingsScreenState(): SettingsScreenState {
    val searchResults = toSearchResultsSettingsState()
    val searchEngines = toSearchEngineSettingsState()
    val fileSearch = toFileSearchSettingsState()
    val appearance = toAppearanceSettingsState()
    val tools = toToolsSettingsState()
    val appShortcuts = toAppShortcutsSettingsState()

    return SettingsScreenState(
        suggestionExcludedApps = searchResults.suggestionExcludedApps,
        resultExcludedApps = searchResults.resultExcludedApps,
        excludedContacts = searchResults.excludedContacts,
        excludedFiles = searchResults.excludedFiles,
        excludedSettings = searchResults.excludedSettings,
        excludedAppShortcuts = searchResults.excludedAppShortcuts,
        disabledSections = searchResults.disabledSections,
        appSuggestionsEnabled = searchResults.appSuggestionsEnabled,
        enabledAppSuggestionTabs = searchResults.enabledAppSuggestionTabs,
        webSuggestionsEnabled = searchResults.webSuggestionsEnabled,
        webSuggestionsCount = searchResults.webSuggestionsCount,
        topResultIndicatorEnabled = searchResults.topResultIndicatorEnabled,
        topMatchesEnabled = searchResults.topMatchesEnabled,
        topMatchesLimit = searchResults.topMatchesLimit,
        topMatchesSectionOrder = searchResults.topMatchesSectionOrder,
        disabledTopMatchesSections = searchResults.disabledTopMatchesSections,
        recentQueriesEnabled = searchResults.recentQueriesEnabled,
        searchEngineOrder = searchEngines.searchEngineOrder,
        disabledSearchEngines = searchEngines.disabledSearchEngines,
        shortcutCodes = searchEngines.shortcutCodes,
        shortcutEnabled = searchEngines.shortcutEnabled,
        isSearchEngineCompactMode = searchEngines.isSearchEngineCompactMode,
        searchEngineCompactRowCount = searchEngines.searchEngineCompactRowCount,
        isSearchEngineAliasSuffixEnabled = searchEngines.isSearchEngineAliasSuffixEnabled,
        isAliasTriggerAfterSpaceEnabled = searchEngines.isAliasTriggerAfterSpaceEnabled,
        amazonDomain = searchEngines.amazonDomain,
        hasApiKey = searchEngines.hasApiKey,
        geminiApiKeyLast4 = searchEngines.geminiApiKeyLast4,
        llmApiKeyLast4ByProvider = searchEngines.llmApiKeyLast4ByProvider,
        customLlmBaseUrlByProvider = searchEngines.customLlmBaseUrlByProvider,
        customLlmAdvancedPayloadByProvider = searchEngines.customLlmAdvancedPayloadByProvider,
        aiSearchLlmProviderId = searchEngines.aiSearchLlmProviderId,
        isSavingGeminiApiKey = searchEngines.isSavingGeminiApiKey,
        personalContext = searchEngines.personalContext,
        geminiModel = searchEngines.geminiModel,
        geminiGroundingEnabled = searchEngines.geminiGroundingEnabled,
        geminiThinkingEnabled = searchEngines.geminiThinkingEnabled,
        availableGeminiModels = searchEngines.availableGeminiModels,
        availableLlmModelsByProvider = searchEngines.availableLlmModelsByProvider,
        enabledFileTypes = fileSearch.enabledFileTypes,
        showFolders = fileSearch.showFolders,
        filePreviewsEnabled = fileSearch.filePreviewsEnabled,
        showSystemFiles = fileSearch.showSystemFiles,
        folderWhitelistPatterns = fileSearch.folderWhitelistPatterns,
        folderBlacklistPatterns = fileSearch.folderBlacklistPatterns,
        excludedFileExtensions = fileSearch.excludedFileExtensions,
        oneHandedMode = appearance.oneHandedMode,
        bottomSearchBarEnabled = appearance.bottomSearchBarEnabled,
        unifiedPinnedItemsEnabled = appearance.unifiedPinnedItemsEnabled,
        searchHintsEnabled = appearance.searchHintsEnabled,
        settingsIconEnabled = appearance.settingsIconEnabled,
        overlayModeEnabled = appearance.overlayModeEnabled,
        hasSeenOverlayAssistantTip = appearance.hasSeenOverlayAssistantTip,
        hasWallpaperPermission = appearance.hasWallpaperPermission,
        wallpaperAvailable = appearance.wallpaperAvailable,
        wallpaperBackgroundAlpha = appearance.wallpaperBackgroundAlpha,
        wallpaperBlurRadius = appearance.wallpaperBlurRadius,
        appTheme = appearance.appTheme,
        overlayThemeIntensity = appearance.overlayThemeIntensity,
        appThemeMode = appearance.appThemeMode,
        fontScaleMultiplier = appearance.fontScaleMultiplier,
        useSystemFont = appearance.useSystemFont,
        backgroundSource = appearance.backgroundSource,
        customImageUri = appearance.customImageUri,
        selectedIconPackPackage = appearance.selectedIconPackPackage,
        availableIconPacks = appearance.availableIconPacks,
        maskUnsupportedIconPackIcons = appearance.maskUnsupportedIconPackIcons,
        showAppLabels = appearance.showAppLabels,
        phoneAppGridColumns = appearance.phoneAppGridColumns,
        appIconSizeStep = appearance.appIconSizeStep,
        appIconShape = appearance.appIconShape,
        launcherAppIcon = appearance.launcherAppIcon,
        themedIconsEnabled = appearance.themedIconsEnabled,
        deviceThemeEnabled = appearance.deviceThemeEnabled,
        wallpaperAccentEnabled = appearance.wallpaperAccentEnabled,
        openKeyboardOnLaunch = appearance.openKeyboardOnLaunch,
        clearQueryOnLaunch = appearance.clearQueryOnLaunch,
        autoCloseOverlay = appearance.autoCloseOverlay,
        calculatorEnabled = tools.calculatorEnabled,
        unitConverterEnabled = tools.unitConverterEnabled,
        dateCalculatorEnabled = tools.dateCalculatorEnabled,
        currencyConverterEnabled = tools.currencyConverterEnabled,
        wordClockEnabled = tools.wordClockEnabled,
        dictionaryEnabled = tools.dictionaryEnabled,
        customTools = tools.customTools,
        disabledCustomToolIds = tools.disabledCustomToolIds,
        taskerIntentTools = tools.taskerIntentTools,
        allAppShortcuts = appShortcuts.allAppShortcuts,
        allDeviceSettings = appShortcuts.allDeviceSettings,
        allApps = appShortcuts.allApps,
        disabledAppShortcutIds = appShortcuts.disabledAppShortcutIds,
        messagingApp = appShortcuts.messagingApp,
        callingApp = appShortcuts.callingApp,
        isWhatsAppInstalled = appShortcuts.isWhatsAppInstalled,
        isTelegramInstalled = appShortcuts.isTelegramInstalled,
        isSignalInstalled = appShortcuts.isSignalInstalled,
        isGoogleMeetInstalled = appShortcuts.isGoogleMeetInstalled,
        directDialEnabled = appShortcuts.directDialEnabled,
        numberSearchEnabled = appShortcuts.numberSearchEnabled,
    )
}

private data class SearchResultsMapperState(
    val suggestionExcludedApps: List<com.tk.quicksearch.search.models.AppInfo>,
    val resultExcludedApps: List<com.tk.quicksearch.search.models.AppInfo>,
    val excludedContacts: List<com.tk.quicksearch.search.models.ContactInfo>,
    val excludedFiles: List<com.tk.quicksearch.search.models.DeviceFile>,
    val excludedSettings: List<com.tk.quicksearch.search.deviceSettings.DeviceSetting>,
    val excludedAppShortcuts: List<com.tk.quicksearch.search.data.AppShortcutRepository.StaticShortcut>,
    val disabledSections: Set<com.tk.quicksearch.search.core.SearchSection>,
    val appSuggestionsEnabled: Boolean,
    val enabledAppSuggestionTabs: Set<com.tk.quicksearch.search.core.AppSuggestionTabType>,
    val webSuggestionsEnabled: Boolean,
    val webSuggestionsCount: Int,
    val topResultIndicatorEnabled: Boolean,
    val topMatchesEnabled: Boolean,
    val topMatchesLimit: Int,
    val topMatchesSectionOrder: List<com.tk.quicksearch.search.core.SearchSection>,
    val disabledTopMatchesSections: Set<com.tk.quicksearch.search.core.SearchSection>,
    val recentQueriesEnabled: Boolean,
)

private fun SearchUiState.toSearchResultsSettingsState() =
    SearchResultsMapperState(
        suggestionExcludedApps = suggestionExcludedApps,
        resultExcludedApps = resultExcludedApps,
        excludedContacts = excludedContacts,
        excludedFiles = excludedFiles,
        excludedSettings = excludedSettings,
        excludedAppShortcuts = excludedAppShortcuts,
        disabledSections = disabledSections,
        appSuggestionsEnabled = appSuggestionsEnabled,
        enabledAppSuggestionTabs = enabledAppSuggestionTabs,
        webSuggestionsEnabled = webSuggestionsEnabled,
        webSuggestionsCount = webSuggestionsCount,
        topResultIndicatorEnabled = topResultIndicatorEnabled,
        topMatchesEnabled = topMatchesEnabled,
        topMatchesLimit = topMatchesLimit,
        topMatchesSectionOrder = topMatchesSectionOrder,
        disabledTopMatchesSections = disabledTopMatchesSections,
        recentQueriesEnabled = recentQueriesEnabled,
    )

private data class SearchEngineMapperState(
    val searchEngineOrder: List<com.tk.quicksearch.search.core.SearchTarget>,
    val disabledSearchEngines: Set<String>,
    val shortcutCodes: Map<String, String>,
    val shortcutEnabled: Map<String, Boolean>,
    val isSearchEngineCompactMode: Boolean,
    val searchEngineCompactRowCount: Int,
    val isSearchEngineAliasSuffixEnabled: Boolean,
    val isAliasTriggerAfterSpaceEnabled: Boolean,
    val amazonDomain: String?,
    val hasApiKey: Boolean,
    val geminiApiKeyLast4: String?,
    val llmApiKeyLast4ByProvider: Map<AiSearchLlmProviderId, String>,
    val customLlmBaseUrlByProvider: Map<AiSearchLlmProviderId, String>,
    val customLlmAdvancedPayloadByProvider: Map<AiSearchLlmProviderId, Pair<Boolean, String>>,
    val aiSearchLlmProviderId: AiSearchLlmProviderId,
    val isSavingGeminiApiKey: Boolean,
    val personalContext: String,
    val geminiModel: String,
    val geminiGroundingEnabled: Boolean,
    val geminiThinkingEnabled: Boolean,
    val availableGeminiModels: List<com.tk.quicksearch.tools.aiSearch.GeminiTextModel>,
    val availableLlmModelsByProvider: Map<AiSearchLlmProviderId, List<com.tk.quicksearch.tools.aiSearch.GeminiTextModel>>,
)

private fun SearchUiState.toSearchEngineSettingsState() =
    SearchEngineMapperState(
        searchEngineOrder = searchTargetsOrder,
        disabledSearchEngines = disabledSearchTargetIds,
        shortcutCodes = shortcutCodes,
        shortcutEnabled = shortcutEnabled,
        isSearchEngineCompactMode = isSearchEngineCompactMode,
        searchEngineCompactRowCount = searchEngineCompactRowCount,
        isSearchEngineAliasSuffixEnabled = isSearchEngineAliasSuffixEnabled,
        isAliasTriggerAfterSpaceEnabled = isAliasTriggerAfterSpaceEnabled,
        amazonDomain = amazonDomain,
        hasApiKey = hasApiKey,
        geminiApiKeyLast4 = geminiApiKeyLast4,
        llmApiKeyLast4ByProvider = llmApiKeyLast4ByProvider,
        customLlmBaseUrlByProvider = customLlmBaseUrlByProvider,
        customLlmAdvancedPayloadByProvider = customLlmAdvancedPayloadByProvider,
        aiSearchLlmProviderId = aiSearchLlmProviderId,
        isSavingGeminiApiKey = isSavingGeminiApiKey,
        personalContext = personalContext,
        geminiModel = geminiModel,
        geminiGroundingEnabled = geminiGroundingEnabled,
        geminiThinkingEnabled = geminiThinkingEnabled,
        availableGeminiModels = availableGeminiModels,
        availableLlmModelsByProvider = availableLlmModelsByProvider,
    )

private data class FileSearchMapperState(
    val enabledFileTypes: Set<com.tk.quicksearch.search.models.FileType>,
    val showFolders: Boolean,
    val filePreviewsEnabled: Boolean,
    val showSystemFiles: Boolean,
    val folderWhitelistPatterns: Set<String>,
    val folderBlacklistPatterns: Set<String>,
    val excludedFileExtensions: Set<String>,
)

private fun SearchUiState.toFileSearchSettingsState() =
    FileSearchMapperState(
        enabledFileTypes = enabledFileTypes,
        showFolders = showFolders,
        filePreviewsEnabled = filePreviewsEnabled,
        showSystemFiles = showSystemFiles,
        folderWhitelistPatterns = folderWhitelistPatterns,
        folderBlacklistPatterns = folderBlacklistPatterns,
        excludedFileExtensions = excludedFileExtensions,
    )

private data class AppearanceMapperState(
    val oneHandedMode: Boolean,
    val bottomSearchBarEnabled: Boolean,
    val unifiedPinnedItemsEnabled: Boolean,
    val searchHintsEnabled: Boolean,
    val settingsIconEnabled: Boolean,
    val overlayModeEnabled: Boolean,
    val hasSeenOverlayAssistantTip: Boolean,
    val hasWallpaperPermission: Boolean,
    val wallpaperAvailable: Boolean,
    val wallpaperBackgroundAlpha: Float,
    val wallpaperBlurRadius: Float,
    val appTheme: com.tk.quicksearch.search.core.AppTheme,
    val overlayThemeIntensity: Float,
    val appThemeMode: com.tk.quicksearch.search.core.AppThemeMode,
    val fontScaleMultiplier: Float,
    val useSystemFont: Boolean,
    val backgroundSource: com.tk.quicksearch.search.core.BackgroundSource,
    val customImageUri: String?,
    val selectedIconPackPackage: String?,
    val availableIconPacks: List<com.tk.quicksearch.search.core.IconPackInfo>,
    val maskUnsupportedIconPackIcons: Boolean,
    val showAppLabels: Boolean,
    val phoneAppGridColumns: Int,
    val appIconSizeStep: Int,
    val appIconShape: com.tk.quicksearch.search.core.AppIconShape,
    val launcherAppIcon: com.tk.quicksearch.search.core.LauncherAppIcon,
    val themedIconsEnabled: Boolean,
    val deviceThemeEnabled: Boolean,
    val wallpaperAccentEnabled: Boolean,
    val openKeyboardOnLaunch: Boolean,
    val clearQueryOnLaunch: Boolean,
    val autoCloseOverlay: Boolean,
)

private fun SearchUiState.toAppearanceSettingsState() =
    AppearanceMapperState(
        oneHandedMode = oneHandedMode,
        bottomSearchBarEnabled = bottomSearchBarEnabled,
        unifiedPinnedItemsEnabled = unifiedPinnedItemsEnabled,
        searchHintsEnabled = searchHintsEnabled,
        settingsIconEnabled = settingsIconEnabled,
        overlayModeEnabled = overlayModeEnabled,
        hasSeenOverlayAssistantTip = hasSeenOverlayAssistantTip,
        hasWallpaperPermission = hasWallpaperPermission,
        wallpaperAvailable = wallpaperAvailable,
        wallpaperBackgroundAlpha = wallpaperBackgroundAlpha,
        wallpaperBlurRadius = wallpaperBlurRadius,
        appTheme = appTheme,
        overlayThemeIntensity = overlayThemeIntensity,
        appThemeMode = appThemeMode,
        fontScaleMultiplier = fontScaleMultiplier,
        useSystemFont = useSystemFont,
        backgroundSource = backgroundSource,
        customImageUri = customImageUri,
        selectedIconPackPackage = selectedIconPackPackage,
        availableIconPacks = availableIconPacks,
        maskUnsupportedIconPackIcons = maskUnsupportedIconPackIcons,
        showAppLabels = showAppLabels,
        phoneAppGridColumns = phoneAppGridColumns,
        appIconSizeStep = appIconSizeStep,
        appIconShape = appIconShape,
        launcherAppIcon = launcherAppIcon,
        themedIconsEnabled = themedIconsEnabled,
        deviceThemeEnabled = deviceThemeEnabled,
        wallpaperAccentEnabled = wallpaperAccentEnabled,
        openKeyboardOnLaunch = openKeyboardOnLaunch,
        clearQueryOnLaunch = clearQueryOnLaunch,
        autoCloseOverlay = autoCloseOverlay,
    )

private data class ToolsMapperState(
    val calculatorEnabled: Boolean,
    val unitConverterEnabled: Boolean,
    val dateCalculatorEnabled: Boolean,
    val currencyConverterEnabled: Boolean,
    val wordClockEnabled: Boolean,
    val dictionaryEnabled: Boolean,
    val customTools: List<CustomTool>,
    val disabledCustomToolIds: Set<String>,
    val taskerIntentTools: List<com.tk.quicksearch.tools.tasker.TaskerIntentTool>,
)

private fun SearchUiState.toToolsSettingsState() =
    ToolsMapperState(
        calculatorEnabled = calculatorEnabled,
        unitConverterEnabled = unitConverterEnabled,
        dateCalculatorEnabled = dateCalculatorEnabled,
        currencyConverterEnabled = currencyConverterEnabled,
        wordClockEnabled = wordClockEnabled,
        dictionaryEnabled = dictionaryEnabled,
        customTools = customTools,
        disabledCustomToolIds = disabledCustomToolIds,
        taskerIntentTools = taskerIntentTools,
    )

private data class AppShortcutsMapperState(
    val allAppShortcuts: List<com.tk.quicksearch.search.data.AppShortcutRepository.StaticShortcut>,
    val allDeviceSettings: List<com.tk.quicksearch.search.deviceSettings.DeviceSetting>,
    val allApps: List<com.tk.quicksearch.search.models.AppInfo>,
    val disabledAppShortcutIds: Set<String>,
    val messagingApp: com.tk.quicksearch.search.core.MessagingApp,
    val callingApp: com.tk.quicksearch.search.core.CallingApp,
    val isWhatsAppInstalled: Boolean,
    val isTelegramInstalled: Boolean,
    val isSignalInstalled: Boolean,
    val isGoogleMeetInstalled: Boolean,
    val directDialEnabled: Boolean,
    val numberSearchEnabled: Boolean,
)

private fun SearchUiState.toAppShortcutsSettingsState() =
    AppShortcutsMapperState(
        allAppShortcuts = allAppShortcuts,
        allDeviceSettings = allDeviceSettings,
        allApps = allApps,
        disabledAppShortcutIds = disabledAppShortcutIds,
        messagingApp = messagingApp,
        callingApp = callingApp,
        isWhatsAppInstalled = isWhatsAppInstalled,
        isTelegramInstalled = isTelegramInstalled,
        isSignalInstalled = isSignalInstalled,
        isGoogleMeetInstalled = isGoogleMeetInstalled,
        directDialEnabled = directDialEnabled,
        numberSearchEnabled = numberSearchEnabled,
    )
