package com.tk.quicksearch.settings.shared

import com.tk.quicksearch.search.core.*

/**
 * Data class to hold all settings screen state and callbacks. Reduces parameter count and improves
 * maintainability.
 */
data class SettingsScreenState(
    val suggestionExcludedApps: List<com.tk.quicksearch.search.models.AppInfo>,
    val resultExcludedApps: List<com.tk.quicksearch.search.models.AppInfo>,
    val excludedContacts: List<com.tk.quicksearch.search.models.ContactInfo>,
    val excludedFiles: List<com.tk.quicksearch.search.models.DeviceFile>,
    val excludedSettings: List<com.tk.quicksearch.search.deviceSettings.DeviceSetting>,
    val excludedAppShortcuts: List<com.tk.quicksearch.search.data.StaticShortcut>,
    val searchEngineOrder: List<SearchTarget>,
    val disabledSearchEngines: Set<String>,
    val enabledFileTypes: Set<com.tk.quicksearch.search.models.FileType>,
    val showFolders: Boolean,
    val showSystemFiles: Boolean,
    val showHiddenFiles: Boolean,
    val excludedFileExtensions: Set<String>,
    val keyboardAlignedLayout: Boolean,
    val shortcutCodes: Map<String, String>,
    val shortcutEnabled: Map<String, Boolean>,
    val messagingApp: MessagingApp,
    val isWhatsAppInstalled: Boolean,
    val isTelegramInstalled: Boolean,
    val showWallpaperBackground: Boolean,
    val wallpaperBackgroundAlpha: Float,
    val wallpaperBlurRadius: Float,
    val selectedIconPackPackage: String? = null,
    val availableIconPacks: List<IconPackInfo> = emptyList(),
    val showAllResults: Boolean,
    val directDialEnabled: Boolean,
    val sectionOrder: List<SearchSection>,
    val disabledSections: Set<SearchSection>,
    val isSearchEngineCompactMode: Boolean,
    val amazonDomain: String? = null,
    val calculatorEnabled: Boolean,
    val webSuggestionsEnabled: Boolean,
    val webSuggestionsCount: Int,
    val recentQueriesEnabled: Boolean,
    val recentQueriesCount: Int,
    val hasGeminiApiKey: Boolean = false,
    val geminiApiKeyLast4: String? = null,
    val personalContext: String = ""
)

/** Data class to hold all settings screen callbacks. */
data class SettingsScreenCallbacks(
    val onBack: () -> Unit,
    val onRemoveSuggestionExcludedApp: (com.tk.quicksearch.search.models.AppInfo) -> Unit,
    val onRemoveResultExcludedApp: (com.tk.quicksearch.search.models.AppInfo) -> Unit,
    val onRemoveExcludedContact: (com.tk.quicksearch.search.models.ContactInfo) -> Unit,
    val onRemoveExcludedFile: (com.tk.quicksearch.search.models.DeviceFile) -> Unit,
    val onRemoveExcludedSetting: (com.tk.quicksearch.search.deviceSettings.DeviceSetting) -> Unit,
    val onRemoveExcludedAppShortcut: (com.tk.quicksearch.search.data.StaticShortcut) -> Unit,
    val onClearAllExclusions: () -> Unit,
    val onToggleSearchEngine: (SearchTarget, Boolean) -> Unit,
    val onReorderSearchEngines: (List<SearchTarget>) -> Unit,
    val onToggleFileType: (com.tk.quicksearch.search.models.FileType, Boolean) -> Unit,
    val onToggleFolders: (Boolean) -> Unit,
    val onToggleSystemFiles: (Boolean) -> Unit,
    val onToggleHiddenFiles: (Boolean) -> Unit,
    val onRemoveExcludedFileExtension: (String) -> Unit,
    val onToggleKeyboardAlignedLayout: (Boolean) -> Unit,
    val setShortcutCode: (SearchTarget, String) -> Unit,
    val setShortcutEnabled: (SearchTarget, Boolean) -> Unit,
    val onSetMessagingApp: (MessagingApp) -> Unit,
    val onToggleShowWallpaperBackground: (Boolean) -> Unit,
    val onWallpaperBackgroundAlphaChange: (Float) -> Unit,
    val onWallpaperBlurRadiusChange: (Float) -> Unit,
    val onSelectIconPack: (String?) -> Unit,
    val onSearchIconPacks: () -> Unit,
    val onRefreshIconPacks: () -> Unit,
    val onToggleShowAllResults: (Boolean) -> Unit,
    val onToggleDirectDial: (Boolean) -> Unit,
    val onToggleSection: (SearchSection, Boolean) -> Unit,
    val onReorderSections: (List<SearchSection>) -> Unit,
    val onToggleSearchEngineCompactMode: (Boolean) -> Unit,
    val onSetAmazonDomain: (String?) -> Unit,
    val onToggleCalculator: (Boolean) -> Unit,
    val onToggleWebSuggestions: (Boolean) -> Unit,
    val onWebSuggestionsCountChange: (Int) -> Unit,
    val onToggleRecentQueries: (Boolean) -> Unit,
    val onRecentQueriesCountChange: (Int) -> Unit,
    val onSetGeminiApiKey: (String?) -> Unit,
    val onSetPersonalContext: (String?) -> Unit,
    val onAddQuickSettingsTile: () -> Unit,
    val onSetDefaultAssistant: () -> Unit,
    val onRefreshApps: (Boolean) -> Unit,
    val onRefreshContacts: (Boolean) -> Unit,
    val onRefreshFiles: (Boolean) -> Unit,
    val onRequestUsagePermission: () -> Unit,
    val onRequestContactPermission: () -> Unit,
    val onRequestFilePermission: () -> Unit,
    val onRequestCallPermission: () -> Unit
)