package com.tk.quicksearch.settings.shared

import com.tk.quicksearch.search.core.SearchUiState

internal fun SearchUiState.toSettingsScreenState(): SettingsScreenState =
    SettingsScreenState(
        suggestionExcludedApps = suggestionExcludedApps,
        resultExcludedApps = resultExcludedApps,
        excludedContacts = excludedContacts,
        excludedFiles = excludedFiles,
        excludedSettings = excludedSettings,
        excludedAppShortcuts = excludedAppShortcuts,
        searchEngineOrder = searchTargetsOrder,
        disabledSearchEngines = disabledSearchTargetIds,
        enabledFileTypes = enabledFileTypes,
        showFolders = showFolders,
        showSystemFiles = showSystemFiles,
        showHiddenFiles = showHiddenFiles,
        folderWhitelistPatterns = folderWhitelistPatterns,
        folderBlacklistPatterns = folderBlacklistPatterns,
        excludedFileExtensions = excludedFileExtensions,
        oneHandedMode = oneHandedMode,
        bottomSearchBarEnabled = bottomSearchBarEnabled,
        overlayModeEnabled = overlayModeEnabled,
        hasSeenOverlayAssistantTip = hasSeenOverlayAssistantTip,
        shortcutCodes = shortcutCodes,
        shortcutEnabled = shortcutEnabled,
        allAppShortcuts = allAppShortcuts,
        allDeviceSettings = allDeviceSettings,
        allApps = allApps,
        disabledAppShortcutIds = disabledAppShortcutIds,
        messagingApp = messagingApp,
        callingApp = callingApp,
        isWhatsAppInstalled = isWhatsAppInstalled,
        isTelegramInstalled = isTelegramInstalled,
        isSignalInstalled = isSignalInstalled,
        isGoogleMeetInstalled = isGoogleMeetInstalled,
        hasWallpaperPermission = hasWallpaperPermission,
        wallpaperAvailable = wallpaperAvailable,
        wallpaperBackgroundAlpha = wallpaperBackgroundAlpha,
        wallpaperBlurRadius = wallpaperBlurRadius,
        overlayGradientTheme = overlayGradientTheme,
        overlayThemeIntensity = overlayThemeIntensity,
        fontScaleMultiplier = fontScaleMultiplier,
        backgroundSource = backgroundSource,
        customImageUri = customImageUri,
        selectedIconPackPackage = selectedIconPackPackage,
        availableIconPacks = availableIconPacks,
        showAppLabels = showAppLabels,
        directDialEnabled = directDialEnabled,
        disabledSections = disabledSections,
        isSearchEngineCompactMode = isSearchEngineCompactMode,
        searchEngineCompactRowCount = searchEngineCompactRowCount,
        amazonDomain = amazonDomain,
        calculatorEnabled = calculatorEnabled,
        appSuggestionsEnabled = appSuggestionsEnabled,
        webSuggestionsEnabled = webSuggestionsEnabled,
        webSuggestionsCount = webSuggestionsCount,
        openKeyboardOnLaunch = openKeyboardOnLaunch,
        clearQueryOnLaunch = clearQueryOnLaunch,
        recentQueriesEnabled = recentQueriesEnabled,
        hasGeminiApiKey = hasGeminiApiKey,
        geminiApiKeyLast4 = geminiApiKeyLast4,
        personalContext = personalContext,
        geminiModel = geminiModel,
        geminiGroundingEnabled = geminiGroundingEnabled,
        availableGeminiModels = availableGeminiModels,
    )
